prowjob_namespace: prow
pod_namespace: test-pods

in_repo_config:
  enabled:
    nephio-zakaraj/prow-test: true
    nephio-zakaraj/build-test: true
  allowed_clusters:
    "*": ["default"]

deck:
  spyglass:
    lenses:
    - lens:
        name: metadata
      required_files:
      - ^(?:started|finished)\.json$
      optional_files:
      - ^(?:podinfo|prowjob)\.json$
    - lens:
        config:
        name: buildlog
      required_files:
      - build-log.txt
    - lens:
        name: junit
      required_files:
      - .*/junit.*\.xml
    - lens:
        name: podinfo
      required_files:
      - podinfo.json

plank:
  job_url_prefix_config:
    "*": https://prow.arajguru.dev/view/
  report_templates:
    '*': >-
      [Full PR test history](https:/prow.arajguru.dev/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://prow.arajguru.dev/pr?query=is:pr+state:open+author:{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_config_entries:
  - config:
      gcs_configuration:
        bucket: gs://nephio-akash-bucket
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
      github_api_endpoints:
      - http://ghproxy
      - https://api.github.com
      github_app_id: "350959"
      github_app_private_key_secret:
        name: github-token
        key: cert
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20230613-9df263832f
        entrypoint: gcr.io/k8s-prow/entrypoint:v20230613-9df263832f
        initupload: gcr.io/k8s-prow/initupload:v20230613-9df263832f
        sidecar: gcr.io/k8s-prow/sidecar:v20230613-9df263832f

tide:
  queries:
  - labels:
    - lgtm
    - approved
    missingLabels:
    - needs-rebase
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    orgs:
    - nephio-zakaraj
  merge_method:
    nephio-project/build-test: squash
    nephio-project/prow-test: squash

presubmits:
  nephio-zakaraj/prow-test:
  - name: presubmit-prow-test-inrepoconfig-validation
    annotations:
    labels:
    run_if_changed: '.prow.yaml|.prow/'
    skip_report: false
    decorate: true
    cluster: default
    spec:
      containers:
        - image: "gcr.io/k8s-prow/checkconfig:v20221208-8898931a7f"
          command:
            - "checkconfig"
          args:
            - "--plugin-config=../prow-test/prow/config/plugins.yaml"
            - "--config-path=../prow-test/prow/config/config.yaml"

postsubmits:
  nephio-zakaraj/prow-test:
  - name: pull-job
    always_run: true
    decorate: true
    spec:
      containers:
      - image: alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/date"]

