apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods

    deck:
     spyglass:
       lenses:
       - lens:
           name: metadata
         required_files:
         - started.json|finished.json
       - lens:
           config:
           name: buildlog
         required_files:
         - build-log.txt
       - lens:
           name: junit
         required_files:
         - .*/junit.*\.xml
       - lens:
           name: podinfo
         required_files:
         - podinfo.json

    plank:
      job_url_prefix_config:
        "*": https://prow.arajguru.dev/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow.arajguru.dev/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow.arajguru.dev/pr?query=is:pr+state:open+author:{{with
            index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_configs:
        - config:
            gcs_configuration:
              bucket: gs://nephio-prow-bucket
              path_strategy: explicit
            gcs_credentials_secret: gcs-credentials
            github_api_endpoints:
              - http://ghproxy
              - https://api.github.com
            github_app_id: "350959"
            github_app_private_key_secret:
              name: github-token
              key: cert
            utility_images:
              clonerefs: gcr.io/k8s-prow/clonerefs:v20221208-8898931a7f
              entrypoint: gcr.io/k8s-prow/entrypoint:v20221208-8898931a7f
              initupload: gcr.io/k8s-prow/initupload:v20221208-8898931a7f
              sidecar: gcr.io/k8s-prow/sidecar:v20221208-8898931a7f

    tide:
      queries:
      - labels:
        - lgtm
        - approved
        missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        orgs:
        - nephio-zakaraj
      merge_method:
        nephio-zakaraj/build-test: squash
        nephio-zakaraj/prow-test: squash
        nephio-zakaraj/nephio-test-prow-project: squash

    decorate_all_jobs: true
    # periodics:

    postsubmits:
      nephio-zakaraj/nephio-test-prow-project:
      - name: test-postsubmit
        decorate: true
        spec:
          containers:
            - image: alpine
              command:
                - /bin/printenv
    presubmits:
      nephio-zakaraj/nephio-test-prow-project:
      - name: test-presubmit
        decorate: true
        always_run: true
        spec:
          containers:
            - image: alpine
              command:
                - /bin/printenv

